//
//  ContactListTableViewCell.swift
//  Contacts
//
//  Created by Ari Munandar on 4/24/17.
//  Copyright (c) 2017 Ari Munandar. All rights reserved.
//
//  This file was generated by the Devcast Studio XCode Templates
//	Name		: Ari Muandnar
//	E-Mail		: arimunandar.dev@gmail.com
// 	Instagram	: _arymunandar_
// 	Youtube		: https://www.youtube.com/channel/UC7jr8DR06tcVR0QKKl6cSNA
//

import UIKit
import EasyPeasy
import Kingfisher

class ContactListTableViewCell: BaseTableCell {

    // MARK - Initial Label
    var contactName: UILabel = {
        let label = UILabel()
        label.text = NSLocalizedString("Contact Name", comment: "")
        label.textColor = Colors.BLACK
        label.backgroundColor = Colors.CLEAR
        label.font = UIFont(name: "SanFranciscoText-Bold", size: FontSize.MEDIUM)
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()

    // MARK - Initial Image View
    var profileImage: UIImageView = {
        let img = UIImageView()
        img.image = UIImage(named: Icons.GENERAL_NO_IMAGE)?.withRenderingMode(.alwaysOriginal)
        img.tintColor = Colors.DARK_GREY
        img.contentMode = .scaleAspectFill
        img.clipsToBounds = true
        img.layer.cornerRadius = Sizes._20
        img.translatesAutoresizingMaskIntoConstraints = false
        return img
    }()

    // MARK - Initial Button
    var favoriteImage: UIImageView = {
        let img = UIImageView()
        img.image = UIImage(named: Icons.GENERAL_STAR)?.withRenderingMode(.alwaysTemplate)
        img.tintColor = Colors.LIGHT_GREY_2
        img.contentMode = .scaleAspectFill
        img.clipsToBounds = true
        img.translatesAutoresizingMaskIntoConstraints = false
        return img
    }()

    var setContact: ContactListEntity? {
        didSet {
            guard let firstName = setContact?.firstName else {
                return
            }

            guard let lastName = setContact?.lastName else {
                return
            }

            guard let image = setContact?.profilePic else {
                return
            }

            guard let favorite = setContact?.favorite else {
                return
            }

            self.contactName.text = "\(firstName.capitalizingFirstLetter()) \(lastName.capitalizingFirstLetter())"
            let url = URL(string: "\(Route.baseUrl)/\(image)")
            self.profileImage.kf.setImage(with: url)

            if favorite {
                self.favoriteImage.tintColor = Colors.GREEN
            } else {
                self.favoriteImage.tintColor = Colors.LIGHT_GREY_2
            }

        }
    }

    // MARK - Setup Selection Cell
    override var isSelected: Bool {
        didSet {
            if isSelected {
                // Do someting...
            } else {
                // Do someting...
            }
        }
    }

    // MARK - Lifecycle
    override func setupViews() {
        super.setupViews()

        // MARK - Call Setup Cell Properties
        setupProperties()

        // MARK - Call Setup Cell function
        setupComponent()

        // MARK - Call Setup Cell Frame
        setupFrame()

    }

}

// MARK - Setup Component View
extension ContactListTableViewCell {

    // MARK - Setup Cell Properties
    func setupProperties() {
        self.setupGeneral(separatorWidth: Padding._16, bgColor: Colors.LIGHT_GREY_2)
    }

    // MARK - Setup Cell Component
    func setupComponent() {
        self.addSubview(self.profileImage)
        self.addSubview(self.favoriteImage)
        self.addSubview(self.contactName)
    }

    // MARK - Setup Cell frame
    func setupFrame() {
        self.profileImage <- [
            Top(Padding._12),
            Left(Padding._16),
            Size(Sizes._40),
            Bottom(Padding._12)
        ]

        self.favoriteImage <- [
            CenterY(),
            Right(Padding._32),
            Size(Sizes._20)
        ]

        self.contactName <- [
            CenterY(),
            Left(Padding._16).to(self.profileImage),
            Right(Padding._16).to(self.favoriteImage, .left)
        ]
    }

}

// MARK - Setup Component View
extension ContactListTableViewCell {
    // Do someting...
}
