//
//  ContactHeaderCreateOrUpdateTableViewCell.swift
//  Contacts
//
//  Created by Ari Munandar on 4/24/17.
//  Copyright (c) 2017 Ari Munandar. All rights reserved.
//
//  This file was generated by the Devcast Studio XCode Templates
//	Name		: Ari Muandnar
//	E-Mail		: arimunandar.dev@gmail.com
// 	Instagram	: _arymunandar_
// 	Youtube		: https://www.youtube.com/channel/UC7jr8DR06tcVR0QKKl6cSNA
//

import UIKit
import EasyPeasy

class ContactHeaderCreateOrUpdateTableViewCell: BaseTableCell {

    // MARK: - Setup Delegate
    var delegate: ContactCreateOrUpdateViewComponent?

    // MARK - Initial Image View
    var profileImage: UIImageView = {
        let img = UIImageView()
        img.image = UIImage(named: Icons.GENERAL_NO_IMAGE)?.withRenderingMode(.alwaysOriginal)
        img.tintColor = Colors.DARK_GREY
        img.contentMode = .scaleAspectFit
        img.clipsToBounds = true
        img.layer.borderColor = Colors.WHITE.cgColor
        img.layer.borderWidth = 3
        img.layer.cornerRadius = (Sizes.WIDTH - (Sizes._200 + Sizes._50)) / 2
        img.translatesAutoresizingMaskIntoConstraints = false
        return img
    }()

    // MARK - Initial View
    var gradientView: GradientView = {
        let view = GradientView()
        view.colors = [Colors.WHITE, Colors.LIGHT_GREEN]
        return view
    }()

    // MARK - Initial Button
    lazy var cameraButton: UIButton = {
        let button = UIButton()
        button.setImage(UIImage(named: Icons.GENERAL_CAMERA)?.withRenderingMode(.alwaysTemplate), for: .normal)
        button.tintColor = Colors.GREEN
        button.backgroundColor = Colors.WHITE
        button.layer.cornerRadius = Sizes._20
        button.translatesAutoresizingMaskIntoConstraints = false
        button.addTarget(self, action: #selector(handleShowImagePicker), for: .touchUpInside)
        return button
    }()

    var setImage: UIImage? {
        didSet {
            guard let value = setImage else {
                return
            }
            self.profileImage.image = value.withRenderingMode(.alwaysOriginal)
        }
    }

    // MARK - Setup Selection Cell
    override var isSelected: Bool {
        didSet {
            if isSelected {
                // Do someting...
            } else {
                // Do someting...
            }
        }
    }

    // MARK - Lifecycle
    override func setupViews() {
        super.setupViews()

        // MARK: - Cell Setup Cell Properties
        setupProperties()

        // MARK: - Call Setup Cell function
        setupComponent()

        // MARK: - Call Setup Cell Frame
        setupFrame()

    }

}

// MARK - Setup Component View
extension ContactHeaderCreateOrUpdateTableViewCell {

    // MARK - Setup Cell Component
    func setupProperties() {
        self.setupGeneral()
        self.setupGeneral(bgColor: Colors.GREEN)
    }

    // MARK - Setup Cell Component
    func setupComponent() {
        self.addSubview(self.gradientView)
        self.addSubview(self.profileImage)
        self.addSubview(self.cameraButton)
    }

    // MARK - Setup Cell frame
    func setupFrame() {
        self.gradientView <- [
            Top(),
            Left(),
            Right(),
            Bottom()
        ]

        self.profileImage <- [
            CenterX(),
            Top(Sizes._20),
            Size(Sizes.WIDTH - (Sizes._200 + Sizes._50)),
            Bottom(Padding._16 + 2 + Sizes._25)
        ]

        self.cameraButton <- [
            Bottom().to(self.profileImage, .bottom),
            Right().to(self.profileImage, .right),
            Size(Sizes._40)
        ]
    }

}

extension ContactHeaderCreateOrUpdateTableViewCell {
    func handleShowImagePicker() {
        self.delegate?.viewController?.selectPicture()
    }
}

