//
//  BaseCollectionCell.swift
//  Contacts
//
//  Created by Ari Munandar on 4/26/17.
//  Copyright (c) 2017 Ari Munandar. All rights reserved.
//
//  This file was generated by the Etalastic XCode Templates
//	Name		: Ari Muandnar
//	E-Mail		: arimunandar.dev@gmail.com
// 	Instagram	: _arymunandar_
// 	Youtube		: https://www.youtube.com/channel/UC7jr8DR06tcVR0QKKl6cSNA
//

//
//  BaseCollectionCell.swift
//  Promys
//
//  Created by Ari Munandar on 3/6/17.
//  Copyright (c) 2017 Vivere. All rights reserved.
//
//  This file was generated by the Etalastic XCode Templates
//	Name		: Ari Muandnar
//	E-Mail		: arimunandar.dev@gmail.com
// 	Instagram	: _arymunandar_
// 	Youtube		: https://www.youtube.com/channel/UC7jr8DR06tcVR0QKKl6cSNA
//

import UIKit
import EasyPeasy

class BaseCollectionCell: UICollectionViewCell {

    override init(frame: CGRect) {
        super.init(frame: frame)

        // MARK - Call Setup Views function
        setupViews()

    }

    // MARK - Setup Views
    func setupViews() {
        // Do someting...
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

}

