//
//  BaseTableCell.swift
//  Contacts
//
//  Created by Ari Munandar on 4/24/17.
//  Copyright (c) 2017 Ari Munandar. All rights reserved.
//
//  This file was generated by the Etalastic XCode Templates
//	Name		: Ari Muandnar
//	E-Mail		: arimunandar.dev@gmail.com
// 	Instagram	: _arymunandar_
// 	Youtube		: https://www.youtube.com/channel/UC7jr8DR06tcVR0QKKl6cSNA
//

import UIKit

class BaseTableCell: UITableViewCell {

    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)

        setupViews()

    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func setupViews() {

    }

    func setupGeneral(separatorWidth: CGFloat = 0, bgColor: UIColor = Colors.WHITE) {
        self.selectionStyle = .none
        self.backgroundColor = bgColor
        self.layoutMargins = UIEdgeInsets.zero
        self.separatorInset = UIEdgeInsets(top: 0, left: separatorWidth, bottom: 0, right: Padding._16)
    }

}
