//
//  ContactDetailTableViewCell.swift
//  Contacts
//
//  Created by Ari Munandar on 4/25/17.
//  Copyright (c) 2017 Ari Munandar. All rights reserved.
//
//  This file was generated by the Devcast Studio XCode Templates
//	Name		: Ari Muandnar
//	E-Mail		: arimunandar.dev@gmail.com
// 	Instagram	: _arymunandar_
// 	Youtube		: https://www.youtube.com/channel/UC7jr8DR06tcVR0QKKl6cSNA
//

import UIKit
import EasyPeasy

class ContactDetailTableViewCell: BaseTableCell {

    // MARK - Initial Label
    var titleLabel: UILabel = {
        let label = UILabel()
        label.text = NSLocalizedString("Title", comment: "")
        label.textColor = Colors.MID_GREY
        label.backgroundColor = Colors.CLEAR
        label.font = UIFont(name: "SanFranciscoText-Regular", size: FontSize.LARGE)
        label.textAlignment = .right
        label.numberOfLines = 0
        label.lineBreakMode = .byWordWrapping
        label.sizeToFit()
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()

    var valueLabel: UILabel = {
        let label = UILabel()
        label.text = NSLocalizedString("", comment: "")
        label.textColor = Colors.DARK_GREY
        label.backgroundColor = Colors.CLEAR
        label.font = UIFont(name: "SanFranciscoText-Regular", size: FontSize.LARGE)
        label.textAlignment = .left
        label.numberOfLines = 0
        label.lineBreakMode = .byWordWrapping
        label.sizeToFit()
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()

    var setTitle: String? {
        didSet {
            guard let title = setTitle else {
                return
            }

            self.titleLabel.text = title
        }
    }

    var setValue: String? {
        didSet {
            guard let value = setValue else {
                return
            }

            self.valueLabel.text = value
        }
    }

    // MARK - Setup Selection Cell
    override var isSelected: Bool {
        didSet {
            if isSelected {
                // Do someting...
            } else {
                // Do someting...
            }
        }
    }

    // MARK - Lifecycle
    override func setupViews() {
        super.setupViews()

        // MARK: - Call Setup Properties
        setupProperties()

        // MARK - Call Setup Cell function
        setupComponent()

        // MARK - Call Setup Cell Frame
        setupFrame()

    }

}

// MARK - Setup Component View
extension ContactDetailTableViewCell {

    // MARK: - Setup P{roperties
    func setupProperties() {
        self.setupGeneral(separatorWidth: Padding._16)
    }

    // MARK - Setup Cell Component
    func setupComponent() {
        self.addSubview(self.titleLabel)
        self.addSubview(self.valueLabel)
    }

    // MARK - Setup Cell frame
    func setupFrame() {
        self.titleLabel <- [
            Top(Sizes._20),
            Left(Padding._24),
            Width(Sizes._50),
            Bottom(Sizes._20)
        ]

        self.valueLabel <- [
            CenterY(),
            Left(Padding._32).to(self.titleLabel),
            Right(Padding._16)
        ]
    }

}
